# -*- coding: utf-8 -*-
"""sleep-cycle-calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nsuFwt1tLAc8O2hXLOoYhRQSC1Tahvv
"""

!pip install streamlit

import streamlit as st
from datetime import datetime, timedelta

st.title("حاسبة وقت الاستيقاظ حسب دورة النوم")

st.markdown("""
هذه الأداة تساعدك تحسب وقت الاستيقاظ المناسب بناء على دورة النوم للطلاب والي عادة نومهم مرهق.
كل دورة نوم عندهم تستغرق تقريبًا 93 دقيقة.
""")

# إدخال وقت النوم
sleep_time_input = st.time_input("اختر وقت النوم (الوقت اللي بتنام فيه):", value=datetime.now().time())

# تحويل الوقت المدخل إلى datetime
today = datetime.today()
sleep_time = datetime.combine(today, sleep_time_input)

# إدخال عدد الدورات
cycles = st.slider("اختر عدد دورات النوم:", min_value=1, max_value=6, value=5)

# مدة دورة النوم
cycle_minutes = 93
total_sleep = timedelta(minutes=cycle_minutes * cycles)

# حساب وقت الاستيقاظ
wake_time = sleep_time + total_sleep
wake_time_str = wake_time.strftime("%I:%M %p")

# عرض النتيجة
st.subheader("النتيجة:")
st.write(f"إذا نمت الساعة {sleep_time.strftime('%I:%M %p')} واخترت {cycles} دورة نوم،")
st.write(f"أنسب وقت تصحى فيه هو: **{wake_time_str}**")
st.markdown("تم انشاءه بواسطة ميساء الأفضل")